#!/usr/bin/env bash
echo "Warning: bash32 module is deprecated; use bash-kit instead" >&2

dk use: bash-kit

export BASH32_IMAGE=ghcr.io/bashup/bash-kit:3.2
export BASH32_DOCKER_OPTS="-it"

bash32.prepare-image() {
    : # override to e.g. build a custom image or change BASH32_IMAGE/DOCKER_OPTS
}

bash32.bootstrap() {
    : # Redefine this to do any in-container bootstrapping, e.g. to install other packages
}

[[ "${BASHKIT_VERSION-}" != "3.2" ]] || before run-bash bash32.bootstrap

dk.bash32() {
    bash32.prepare-image

    # Figure out what image to use, falling back to BASHKIT_IMAGE
    # if using the default ghcr.io/bashup/bash-kit:3.2 image
    REPLY=$BASH32_IMAGE; [[ $REPLY == *:* ]] || REPLY+=":3.2"
    [[ $REPLY != "ghcr.io/bashup/bash-kit:3.2" ]] || REPLY=$BASHKIT_IMAGE

	# shellcheck disable=SC2034
    local BASHKIT_IMAGE=$REPLY BASHKIT_DOCKER_OPTS=("$BASH32_DOCKER_OPTS")
    dk with-bash 3.2 "$@"
}
