#!/usr/bin/env bash

dk use: tty

[[ -f .cramrc ]] || export CRAM="${CRAM-"--indent=4 --shell=bash --verbose"}"

cram.files() { ls specs/*.cram.md; }
cram.pager() { less -FRX; }
if [[ ${TRAVIS-} == true ]] ; then cram.pager() { cat; } fi

on test_files run cram_files
on cram_files cram.files

on test dk cram

dk.cram() {
    dk bootstrap;
    require cram install-cram
    IFS=$'\n' eval 'local cramfiles=($(run cram_files))'
    tty pager slurpify diffcolor -- cram "$@" ${cramfiles[@]+"${cramfiles[@]}"}
}

install-cram() {
    require-any python
    github pjeby/cram indent-fix
    catbin cram <(
        echo '#!/usr/bin/env bash'
        echo 'PYTHONPATH=$BASHER_PACKAGES_PATH/pjeby/cram python -m cram "$@"'
    )
}

slurpy() {
    # Read the entire output of a pipe, and forward it on (minus NUL bytes)
    # This keeps cram and pygmentize happy and SIGPIPE-free!
    while read -rd ''; do printf "%s" "$REPLY"; done; printf "%s" "$REPLY";
}

diffcolor() { tty-tool COLORDIFF colordiff || tty-tool COLORDIFF pygmentize -l diff; }
slurpify()  { REPLY=slurpy; }
