#!/usr/bin/env bash

[[ -f .cramrc ]] || export CRAM="${CRAM-"--indent=4 --shell=bash --verbose"}"

cram.files() { ls specs/*.cram.md; }
cram.pager() { less -FRX; }
test.files() { cram.files; }

dk.test() { dk cram; }
dk.cram() {
    dk bootstrap;
    require cram install-cram
    IFS=$'\n' eval 'local cramfiles=($(cram.files))'
    if (($#)); then
         cram "$@" "${cramfiles[@]}"
    else cram "${cramfiles[@]}" | {
        if have-any pygmentize; then
            pygmentize -l diff | slurpy
        else
            slurpy
        fi
    } | cram.pager
    fi
}

install-cram() {
    require-any python
    github brodie/cram
    catbin cram <(
        echo '#!/usr/bin/env bash'
        echo 'PYTHONPATH=$BASHER_PACKAGES_PATH/brodie/cram python -m cram "$@"'
    )
}

slurpy() {
    # Read the entire output of a pipe, and forward it on (minus NUL bytes)
    # This keeps cram and pygmentize happy and SIGPIPE-free!
    while read -rd ''; do printf "%s" "$REPLY"; done; printf "%s" "$REPLY";
}
