#!/usr/bin/env bash

dk use: tty

dk.watch() {
    require-any entr abort "Please install entr (http://entrproject.org/) to watch files" 69
    require-any tput
    (($#)) || set -- dk files_changed # default to firing `files_changed` events
    if run watch_files | entr-watch "$@"; (($?==2)); then
        exec dk watch "$@"
    fi
    stty echo
}

on "default_files_changed" dk test
on "watch_files" watch.files

watch.files() {
    { run test_files; ls; } | grep -v '\.md\.err$'
}

entr-watch() {
    # emulate watch's single-screen behavior with entr
    DEVKIT_PAGER=${DEVKIT_PAGER-pager.screenfull} tty -- entr -c -d -s ' '"$*"
}
