#!/usr/bin/env bash

dk.watch() {
    require-any entr abort "Please install entr (http://entrproject.org/) to watch files" 69
    require-any tput
    (($#)) || set -- dk test # default to watching `dk test`
    if watch.files | entr-watch "$@"; (($?==2)); then
        exec dk watch "$@"
    fi
    stty echo
}

watch.files() {
    { run test_files; ls; } | grep -v '\.md\.err$'
}

entr-watch() {
    # emulate watch's single-screen behavior with entr
    entr -c -d -s "$* "'| head -n $(( $(tput lines) - 2 ))'
}
