#!/usr/bin/env bash

dk use: composer tty

peridot.files() { find "$PERIDOT_SPECS" -name '*.spec.php'; }

on "test_files"    run peridot_files
on "peridot_files" peridot.files
on "test"          dk peridot
on "bootstrap"     require-composer peridot peridot-php/peridot

PERIDOT_SPECS=specs

dk.peridot() {
	! isatty || export PERIDOT_TTY=1
	# shellcheck disable=SC2086  # set -f disables globs, and we WANT word splitting
	(set -f; peridot ${PERIDOT_OPTIONS-} "$@" "$PERIDOT_SPECS")
}

paged-command peridot