#!/usr/bin/env bash

export SHELLCHECK_OPTS

have-any shellcheck || shellcheck() {
	docker run --rm -i -e SHELLCHECK_OPTS -v "$PWD":/mnt koalaman/shellcheck "$@"
}

dk.shellcheck() {
	! isatty || set -- "-Calways" "$@"
	shellcheck "$@"
}

paged-command shellcheck