#!/usr/bin/env bash

jq() { if pager; then command jq -C "$@" | $REPLY; else command jq "$@"; fi; }

pager() { tty-tool PAGER less -FRX; }

pager.screenfull() { head -n $(( $(tput lines) - ${1-2} )); }
pager.watch()      { clear; date; echo; pager.screenfull 4; }

diffcolor() { tty-tool COLORDIFF colordiff || tty-tool COLORDIFF pygmentize -l diff; }

tty-tool() {
	isatty || return; set -- "${tty_prefix-DEVKIT_}$@"; REPLY=${!1-};
	if [[ ! ${!1+_} ]] && command -v "$2" >/dev/null; then
		event quote command "${@:2}"
	else [[ $REPLY ]];
	fi
}

isatty() {
	local t=${tty_prefix-DEVKIT_}ISATTY
	if [[ ${!t+_} ]]; then
		case "${!t-}" in 0|"") false ;; ?*) true ;; esac
	else [[ -t 1 ]]
	fi
}

tty() {
	local pipe=
	while (($#)) && [[ $1 != -- ]]; do
		! $1 || pipe="| $REPLY$pipe"; shift
	done
	event quote "${@:2}"
	eval "$REPLY $pipe"
}
