#!/usr/bin/env bash

export CRAM="--indent=4 --shell=bash --verbose"

cramfiles() { ls specs/*.cram.md; }
crampager() { less -FR; }
testfiles() { cramfiles; }

dk.test() { dk cram; }
dk.cram() {
    dk bootstrap;
    have-any cram ||
        abort "Please install cram (https://bitheap.org/cram/) to run tests" 69
    if (($#)); then
         xargs -a <(cramfiles) cram "$@"
    else xargs -a <(cramfiles) cram  | {
        if have-any pygmentize; then
            pygmentize -l diff | slurpy
        else
            slurpy
        fi
    } | crampager
    fi
}

slurpy() {
    # Read the entire output of a pipe, and forward it on (minus NUL bytes)
    # This keeps cram and pygmentize happy and SIGPIPE-free!
    while read -rd ''; do printf "%s" "$REPLY"; done; printf "%s" "$REPLY";
}
