#!/usr/bin/env bash

export CRAM="--indent=4 --shell=bash --verbose"

cram.files() { ls specs/*.cram.md; }
cram.pager() { less -FR; }
test.files() { cram.files; }

dk.test() { dk cram; }
dk.cram() {
    dk bootstrap;
    have-any cram ||
        abort "Please install cram (https://bitheap.org/cram/) to run tests" 69
    if (($#)); then
         xargs -a <(cram.files) cram "$@"
    else xargs -a <(cram.files) cram  | {
        if have-any pygmentize; then
            pygmentize -l diff | slurpy
        else
            slurpy
        fi
    } | cram.pager
    fi
}

slurpy() {
    # Read the entire output of a pipe, and forward it on (minus NUL bytes)
    # This keeps cram and pygmentize happy and SIGPIPE-free!
    while read -rd ''; do printf "%s" "$REPLY"; done; printf "%s" "$REPLY";
}
